angle_fea_len: 80
batch_size: 4
bond_fea_len: 80
checkpoint_every: 100
embedding: false
epochs: 5000
gamma: 0.5
h_fea_angle: 256
h_fea_edge: 256
learning_rate: 0.001
n_classification: 6
n_conv_edge: 2
n_conv_angle: 1
neighbors: 15
num_workers: 0
pin_memory: true
rcut: 6
resume: true
search_delta: 20
search_type: global
step_size: 100
test_size: 0
train_size: 960
val_size: 240
num_MLP: 0
dropout_prob: 0.5
